ALTER TABLE DOMAIN_CHECK ADD COLUMN SOURCE_SYSTEM_NEW CHARACTER VARYING(64);
UPDATE DOMAIN_CHECK SET SOURCE_SYSTEM_NEW = CAST(SOURCE_SYSTEM AS CHARACTER VARYING(64));
ALTER TABLE DOMAIN_CHECK DROP COLUMN SOURCE_SYSTEM;
ALTER TABLE DOMAIN_CHECK ALTER COLUMN SOURCE_SYSTEM_NEW RENAME TO SOURCE_SYSTEM;
ALTER TABLE DOMAIN_CHECK ALTER COLUMN SOURCE_SYSTEM SET NOT NULL;
