CREATE TABLE DONGLE_APPLICATION (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USER_ID BIGINT NOT NULL,
	CREATED BIGINT NOT NULL,

	NAME CHARACTER VARYING(128) NOT NULL,
	STREET CHARACTER VARYING(128) NOT NULL,
	ZIP CHARACTER VARYING(16) NOT NULL,
	CITY CHARACTER VARYING(128) NOT NULL,
	COUNTRY CHARACTER VARYING(64) NOT NULL,

	PROVIDER CHARACTER VARYING(64) NOT NULL,
	PROVIDER_OTHER CHARACTER VARYING(128),
	CONNECTION_TYPE CHARACTER VARYING(32) NOT NULL,
	ROUTER_KIND CHARACTER VARYING(32) NOT NULL,
	ROUTER_MODEL CHARACTER VARYING(128),
	SPAM_FREQUENCY CHARACTER VARYING(16) NOT NULL,

	SKILL_LEVEL CHARACTER VARYING(32),
	ALLOW_PUBLISH BOOLEAN DEFAULT FALSE NOT NULL,

	NOTES CHARACTER VARYING(4096),

	STATUS CHARACTER VARYING(16) DEFAULT 'NEW' NOT NULL,

	CONSTRAINT DONGLE_APPLICATION_PK PRIMARY KEY (ID),
	CONSTRAINT DONGLE_APPLICATION_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE INDEX DONGLE_APPLICATION_USER_IDX ON DONGLE_APPLICATION (USER_ID);
CREATE INDEX DONGLE_APPLICATION_STATUS_IDX ON DONGLE_APPLICATION (STATUS, CREATED);
