ALTER TABLE NUMBERS_AGGREGATION_10 ADD COLUMN SHA1 BINARY VARYING(20);
ALTER TABLE NUMBERS_AGGREGATION_100 ADD COLUMN SHA1 BINARY VARYING(20);
CREATE INDEX AGG10_SHA1_IDX ON NUMBERS_AGGREGATION_10 (SHA1);
CREATE INDEX AGG100_SHA1_IDX ON NUMBERS_AGGREGATION_100 (SHA1);
