ALTER TABLE USERS ADD GOOGLEID CHARACTER VARYING(64);

UPDATE USERS SET GOOGLEID = EXTID WHERE CLIENTNAME = 'Google2Client';

ALTER TABLE USERS ALTER COLUMN EXTID VARCHAR_IGNORECASE(64) NULL;
ALTER TABLE USERS ALTER COLUMN CLIENTNAME VARCHAR_IGNORECASE(64) NULL;

UPDATE USERS SET EMAIL = LOWER(EMAIL);