CREATE TABLE NUMBERS_LOCALE (
	PHONE CHARACTER VARYING(100) NOT NULL,
	DIAL CHARACTER VARYING(8) NOT NULL,
	LASTACCESS BIGINT NOT NULL,
	SEARCHES INTEGER DEFAULT 0 NOT NULL,
	VOTES INTEGER DEFAULT 0 NOT NULL,
	CALLS INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT NUMBERS_LOCALE_PK PRIMARY KEY (PHONE,DIAL)
);
