CREATE TABLE PUBLIC.PROPERTIES (
	NAME CHARACTER VARYING(255) NOT NULL,
	VAL CHARACTER VARYING(1024) NOT NULL,
	CONSTRAINT PROPERTIES_PK PRIMARY KEY (NAME)
);

INSERT INTO PROPERTIES (NAME, VAL) VALUES('db.version', '4');

ALTER TABLE NUMBERS ADD SHA1 BINARY VARYING(20);
CREATE INDEX NUMBERS_SHA1_IDX ON NUMBERS (SHA1, PHONE);

