-- PUBLIC.BLOCKLIST definition

-- Drop table

-- DROP TABLE BLOCKLIST;

CREATE TABLE BLOCKLIST (
	OWNER BIGINT NOT NULL,
	PHONE CHARACTER VARYING(100) NOT NULL,

	CONSTRAINT BLOCKLIST_PK PRIMARY KEY (OWNER,PHONE)
);

-- PUBLIC.EXCLUDES definition

-- Drop table

-- DROP TABLE EXCLUDES;

CREATE TABLE EXCLUDES (
	OWNER BIGINT NOT NULL,
	PHONE CHARACTER VARYING(100) NOT NULL,

	CONSTRAINT EXCLUDES_PK PRIMARY KEY (OWNER,PHONE)
);

-- PUBLIC.SPAMREPORTS definition

-- Drop table

-- DROP TABLE SPAMREPORTS;

CREATE TABLE SPAMREPORTS (
	PHONE VARCHAR(100) NOT NULL,
	VOTES INTEGER DEFAULT 1 NOT NULL,
	LASTUPDATE BIGINT NOT NULL,

	CONSTRAINT SPAMREPORTS_PK PRIMARY KEY (PHONE)
);

-- PUBLIC.USERS definition

-- Drop table

-- DROP TABLE USERS;

CREATE TABLE USERS (
	EMAIL CHARACTER VARYING(255) NOT NULL,
	ID BIGINT NOT NULL AUTO_INCREMENT,
	PWHASH BINARY VARYING(128) NOT NULL,
	LASTACCESS BIGINT DEFAULT 0 NOT NULL,

	CONSTRAINT USERS_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX USERS_UN_INDEX_4 ON USERS (EMAIL);
