-- Migration 03: Replace DISPOSABLE boolean with STATUS varchar in DOMAIN_CHECK.
ALTER TABLE DOMAIN_CHECK ADD COLUMN STATUS CHARACTER VARYING(16);
UPDATE DOMAIN_CHECK SET STATUS = CASE WHEN DISPOSABLE THEN 'disposable' ELSE 'safe' END;
ALTER TABLE DOMAIN_CHECK DROP COLUMN DISPOSABLE;
ALTER TABLE DOMAIN_CHECK ALTER COLUMN STATUS SET NOT NULL;
