CREATE TABLE IF NOT EXISTS DOMAIN_CHECK (
	DOMAIN_NAME CHARACTER VARYING(255) NOT NULL,
	DISPOSABLE BOOLEAN NOT NULL,
	LAST_CHANGED BIGINT NOT NULL,
	SOURCE_SYSTEM CHARACTER VARYING(64) NOT NULL,
	MX_HOST CHARACTER VARYING(255),
	MX_IP CHARACTER VARYING(255),
	CONSTRAINT DOMAIN_CHECK_PK PRIMARY KEY (DOMAIN_NAME)
);

CREATE TABLE IF NOT EXISTS EMAIL_CHECK (
    EMAIL_ADDRESS CHARACTER VARYING(320) NOT NULL,
    DISPOSABLE BOOLEAN NOT NULL,
    LAST_CHECKED BIGINT NOT NULL,
    SOURCE_SYSTEM CHARACTER VARYING(64) NOT NULL,
    CONSTRAINT EMAIL_CHECK_PK PRIMARY KEY (EMAIL_ADDRESS)
);

CREATE TABLE IF NOT EXISTS MX_HOST_STATUS (
    MX_HOST CHARACTER VARYING(255) NOT NULL,
    STATUS CHARACTER VARYING(16) NOT NULL,
    LAST_UPDATED BIGINT NOT NULL,
    CONSTRAINT MX_HOST_STATUS_PK PRIMARY KEY (MX_HOST)
);

CREATE TABLE IF NOT EXISTS MX_IP_STATUS (
    MX_IP CHARACTER VARYING(255) NOT NULL,
    STATUS CHARACTER VARYING(16) NOT NULL,
    LAST_UPDATED BIGINT NOT NULL,
    CONSTRAINT MX_IP_STATUS_PK PRIMARY KEY (MX_IP)
);
