-- Normalize MX_HOST to lowercase in existing DOMAIN_CHECK data.
UPDATE DOMAIN_CHECK SET MX_HOST = LOWER(MX_HOST) WHERE MX_HOST <> LOWER(MX_HOST);

-- Initial population of MX_HOST_STATUS from existing DOMAIN_CHECK data.
-- Idempotent: only inserts hosts/IPs not yet present.
INSERT INTO MX_HOST_STATUS (MX_HOST, MX_IP, STATUS, LAST_UPDATED)
SELECT MX_HOST, MAX(MX_IP),
  CASE
    WHEN MIN(CASE WHEN DISPOSABLE THEN 1 ELSE 0 END) = 1 THEN 'disposable'
    WHEN MAX(CASE WHEN DISPOSABLE THEN 1 ELSE 0 END) = 0 THEN 'safe'
    ELSE 'mixed'
  END,
  MAX(LAST_CHANGED)
FROM DOMAIN_CHECK
WHERE MX_HOST IS NOT NULL AND MX_HOST <> '-'
  AND MX_HOST NOT IN (SELECT MX_HOST FROM MX_HOST_STATUS)
GROUP BY MX_HOST;

-- Initial population of MX_IP_STATUS from existing DOMAIN_CHECK data.
INSERT INTO MX_IP_STATUS (MX_IP, STATUS, LAST_UPDATED)
SELECT MX_IP,
  CASE
    WHEN MIN(CASE WHEN DISPOSABLE THEN 1 ELSE 0 END) = 1 THEN 'disposable'
    WHEN MAX(CASE WHEN DISPOSABLE THEN 1 ELSE 0 END) = 0 THEN 'safe'
    ELSE 'mixed'
  END,
  MAX(LAST_CHANGED)
FROM DOMAIN_CHECK
WHERE MX_IP IS NOT NULL
  AND MX_IP NOT IN (SELECT MX_IP FROM MX_IP_STATUS)
GROUP BY MX_IP;
